### ISSUE TITLE
Error when using ForwardDiff: The applicable method may be too new

### ISSUE THREAD

**Issue by gnangnan15** [rdeits/EnhancedGJK.jl#36]
Hello I would like to use your distance calculation in combination with the ForwardDiff package. But I have following error when trying to do this: 

> ERROR: MethodError: no method matching ForwardDiff.Dual{ForwardDiff.Tag{typeof(distance_from_segment),Float64},Float64,1}(::Int64)
> The applicable method may be too new: running in world age 27852, while current world is 27866.
> Closest candidates are:
>   ForwardDiff.Dual{ForwardDiff.Tag{typeof(distance_from_segment),Float64},Float64,1}(::Number) where {T, V, N}

My simplified test code is:

```
using EnhancedGJK
using GeometryTypes
using ForwardDiff

function distance_from_segment(z)
    p1 = GeometryTypes.Point(4.0, -0.5)
    p2 = GeometryTypes.Point(6.0, 0.0)
    l = GeometryTypes.LineSegment(p1, p2)
    p = GeometryTypes.Point(5.0, z)
    result = EnhancedGJK.gjk(l, p)
    return result.in_collision ? 0.0 : separation_distance(result)
end

ForwardDiff.derivative(distance_from_segment, -1.0)

```
Is there something to change in my code to be able to use ForwardDiff?

Thanks in advance for your help.

**Comment by rdeits** [comment]
You're right--there's a bug in the `@generated` function that shows up in this case. I'll see if I can fix it.

**Comment by tkoolen** [comment]
I think I got it. Just a sec.
