### ISSUE TITLE
GeometryBasics vs GeometryTypes

### ISSUE THREAD

**Issue by weymouth** [rdeits/EnhancedGJK.jl#39]
GeometryTypes has been discontinued in favour of GeometryBasics. I'm interested in used the distance functions in this module, but is there any push to update this to work with `GeometryBasics:AbstractMesh`?

**Comment by sjkelly** [comment]
I commented in the issue on GeometryBasics, but a good approach here would be to add both GeometryTypes and GeometryBasics as dependencies, and have them both `import`ed in the codebase. This should allow for a gradual migration without breaking dependent packages. Of course you get more dependencies, but it seems like a reasonable trade-off for greater compatibility/flexibility.
